name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./CSharp/
    - name: Build
      run: dotnet build -c Release ./CSharp/SocketFlow.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./CSharp/SocketFlow.sln
    - name: Pack
      run: dotnet pack -c Release -o ./pack/ ./CSharp/SocketFlow.sln
    - name: Push to NuGet
      run: dotnet nuget push ./pack/SocketFlow*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
